# Generated by Django 6.1 on 2026-08-09 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The client organization this user belongs to. Not required for STAFF users.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='organizations.organization'),
        ),
    ]
