# Generated by Django 6.1 on 2026-08-09 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('service', models.CharField(choices=[('web_development', 'Web Development'), ('business_automation', 'Business Automation'), ('data_analytics', 'Data Analytics'), ('custom_software', 'Custom Software Development'), ('ai_solutions', 'AI Solutions')], max_length=30)),
                ('project_description', models.TextField()),
                ('budget', models.CharField(blank=True, choices=[('under_1000', 'Under $1,000'), ('1000_5000', '$1,000 – $5,000'), ('5000_15000', '$5,000 – $15,000'), ('15000_plus', '$15,000+')], max_length=20)),
                ('timeline', models.CharField(blank=True, choices=[('asap', 'As soon as possible'), ('1_3_months', '1–3 months'), ('3_6_months', '3–6 months'), ('flexible', 'Flexible')], max_length=20)),
                ('additional_info', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_REVIEW', 'In Review'), ('QUOTED', 'Quoted'), ('CONVERTED', 'Converted'), ('DECLINED', 'Declined')], default='NEW', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Set once staff link this quote to a client User during conversion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
